### ISSUE TITLE
Weird errors when trying to get activity

### ISSUE THREAD

**Issue by Yankees4life** [NiNiyas/JellyPy#1]
Heres the logs. Using the latest version BTW

> 2023-01-31 05:07:36 - INFO :: MainThread : Starting JellyPy 0.8.0-alpha
> 2023-01-31 05:07:36 - INFO :: MainThread : Windows 10 (10.0.19044)
> 2023-01-31 05:07:36 - INFO :: MainThread : America/New_York (UTC-0500)
> 2023-01-31 05:07:36 - INFO :: MainThread : Python 3.9.11 (tags/v3.9.11:2de452f, Mar 16 2022, 14:33:45) [MSC v.1929 64 bit (AMD64)]
> 2023-01-31 05:07:36 - INFO :: MainThread : Program Dir: C:\Users\Jean\Documents\Projects\JellyPy
> 2023-01-31 05:07:36 - INFO :: MainThread : Config File: C:\Users\Jean\Documents\Projects\JellyPy\config.ini
> 2023-01-31 05:07:36 - INFO :: MainThread : Database File: C:\Users\Jean\Documents\Projects\JellyPy\jellypy.db
> 2023-01-31 05:07:36 - INFO :: MainThread : Checking if the database upgrades are required...
> 2023-01-31 05:07:36 - INFO :: MainThread : Checking if configuration upgrades are required...
> 2023-01-31 05:07:36 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in C:\Users\Jean\Documents\Projects\JellyPy
> 2023-01-31 05:07:36 - DEBUG :: MainThread : Git output: b6fd70fdc2597c1ef8c9803c20e72546f09f3823
> 2023-01-31 05:07:36 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref --symbolic-full-name @{u}" with shell in C:\Users\Jean\Documents\Projects\JellyPy
> 2023-01-31 05:07:36 - DEBUG :: MainThread : Git output: origin/master
> 2023-01-31 05:07:36 - INFO :: MainThread : Retrieving latest version information from GitHub
> 2023-01-31 05:07:36 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/NiNiyas/JellyPy/commits/master
> 2023-01-31 05:07:36 - DEBUG :: MainThread : Latest version is b6fd70fdc2597c1ef8c9803c20e72546f09f3823
> 2023-01-31 05:07:36 - INFO :: MainThread : Tautulli is up to date
> 2023-01-31 05:07:36 - INFO :: MainThread : Tautulli NotificationHandler :: Starting background notification handler (2 threads).
> 2023-01-31 05:07:36 - INFO :: MainThread : JellyPy WebStart :: Initializing JellyPy web server...
> 2023-01-31 05:07:36 - INFO :: MainThread : JellyPy WebStart :: Web server authentication is enabled: JellyPy admin (username is 'Je********n').
> 2023-01-31 05:07:36 - INFO :: MainThread : JellyPy WebStart :: Thread Pool Size: 10.
> 2023-01-31 05:07:36 - INFO :: MainThread : JellyPy WebStart :: Starting JellyPy web server on http://0.0.0.0:8181/
> 2023-01-31 05:07:36 - ERROR :: Thread-1 : JellyPy WebSocket :: Failed to check for active sessions: 'CompletionPercentage'.
> 2023-01-31 05:07:36 - WARNING :: Thread-1 : JellyPy WebSocket :: Attempt to fix by flushing temporary sessions...
> 2023-01-31 05:07:36 - INFO :: Thread-1 : JellyPy Database :: Clearing temporary sessions from database.
> 2023-01-31 05:07:36 - DEBUG :: Thread-1 : JellyPy Database :: Clearing database table 'sessions'.
> 2023-01-31 05:07:37 - INFO :: Thread-1 : JellyPy Database :: Vacuuming database.
> 2023-01-31 05:07:37 - INFO :: Thread-4 : JellyPy WebSocket :: Opening websocket.
> 2023-01-31 05:07:37 - INFO :: Thread-1 : JellyPy Users :: Requesting users list refresh...
> 2023-01-31 05:07:37 - INFO :: Thread-4 : JellyPy WebSocket :: Websocket connection successful.
> 2023-01-31 05:07:37 - INFO :: Thread-4 : Scheduled background task: Check GitHub for updates
> 2023-01-31 05:07:37 - INFO :: Thread-4 : Scheduled background task: Optimize JellyPy database
> 2023-01-31 05:07:37 - INFO :: Thread-4 : Scheduled background task: Backup JellyPy database
> 2023-01-31 05:07:37 - INFO :: Thread-4 : Scheduled background task: Backup JellyPy config
> 2023-01-31 05:07:37 - INFO :: Thread-1 : JellyPy Users :: Users list refreshed.
> 2023-01-31 05:07:37 - INFO :: Thread-4 : Scheduled background task: Refresh users list
> 2023-01-31 05:07:37 - INFO :: Thread-1 : JellyPy Libraries :: Requesting libraries list refresh...
> 2023-01-31 05:07:37 - INFO :: Thread-4 : Scheduled background task: Refresh libraries list
> 2023-01-31 05:07:37 - INFO :: Thread-4 : Scheduled background task: Websocket ping
> 2023-01-31 05:07:37 - ERROR :: Thread-1 : Uncaught exception: Traceback (most recent call last):
>   File "C:\Users\Je********n\Documents\Projects\JellyPy\jellypy\logger.py", line 417, in new_run
>     old_run(*args, **kwargs)
>   File "C:\Program Files\Python39\lib\threading.py", line 910, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\Je********n\Documents\Projects\JellyPy\jellypy\__init__.py", line 553, in startup_refresh
>     libraries.refresh_libraries()
>   File "C:\Users\Je********n\Documents\Projects\JellyPy\jellypy\libraries.py", line 50, in refresh_libraries
>     library_sections = jellyconnect.JellyConnect().get_library_details()
>   File "C:\Users\Je********n\Documents\Projects\JellyPy\jellypy\jellyconnect.py", line 3027, in get_library_details
>     server_libraries = self.get_server_children()
>   File "C:\Users\Je********n\Documents\Projects\JellyPy\jellypy\jellyconnect.py", line 2777, in get_server_children
>     'section_type': a['CollectionType'],
> KeyError: 'CollectionType'
> 
> Traceback (most recent call last):
>   File "C:\Users\Jean\Documents\Projects\JellyPy\jellypy\logger.py", line 417, in new_run
>     old_run(*args, **kwargs)
>   File "C:\Program Files\Python39\lib\threading.py", line 910, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\Jean\Documents\Projects\JellyPy\jellypy\__init__.py", line 553, in startup_refresh
>     libraries.refresh_libraries()
>   File "C:\Users\Jean\Documents\Projects\JellyPy\jellypy\libraries.py", line 50, in refresh_libraries
>     library_sections = jellyconnect.JellyConnect().get_library_details()
>   File "C:\Users\Jean\Documents\Projects\JellyPy\jellypy\jellyconnect.py", line 3027, in get_library_details
>     server_libraries = self.get_server_children()
>   File "C:\Users\Jean\Documents\Projects\JellyPy\jellypy\jellyconnect.py", line 2777, in get_server_children
>     'section_type': a['CollectionType'],
> KeyError: 'CollectionType'
> 2023-01-31 05:07:37 - INFO :: MainThread : [31/Jan/2023:05:07:37] ENGINE Serving on http://0.0.0.0:8181
> 2023-01-31 05:07:37 - INFO :: MainThread : Launching Windows system tray icon.
> 2023-01-31 05:07:37 - INFO :: MainThread : Added JellyPy to Windows system startup registry key.
> 2023-01-31 05:07:37 - INFO :: MainThread : JellyPy is ready!
> 2023-01-31 05:09:47 - ERROR :: CP Server Thread-16 : Unable to retrieve data for get_activity: 'CompletionPercentage'
> Traceback (most recent call last):
>   File "C:\Users\Jean\Documents\Projects\JellyPy\jellypy\webserve.py", line 5907, in get_activity
>     result = jellyfin_connect.get_current_activity()
>   File "C:\Users\Jean\Documents\Projects\JellyPy\jellypy\jellyconnect.py", line 2006, in get_current_activity
>     session_output = self.get_session_each(a, skip_cache=skip_cache)
>   File "C:\Users\Jean\Documents\Projects\JellyPy\jellypy\jellyconnect.py", line 2078, in get_session_each
>     transcode_progress = session["TranscodingInfo"]["CompletionPercentage"]
> KeyError: 'CompletionPercentage'
> 2023-01-31 05:09:47 - ERROR :: CP Server Thread-15 : [31/Jan/2023:05:09:47] HTTP
> Traceback (most recent call last):
>   File "C:\Users\Jean\Documents\Projects\JellyPy\lib\cherrypy\_cprequest.py", line 638, in respond
>     self._do_respond(path_info)
>   File "C:\Users\Jean\Documents\Projects\JellyPy\lib\cherrypy\_cprequest.py", line 697, in _do_respond
>     response.body = self.handler()
>   File "C:\Users\Jean\Documents\Projects\JellyPy\lib\cherrypy\lib\encoding.py", line 223, in __call__
>     self.body = self.oldhandler(*args, **kwargs)
>   File "C:\Users\Jean\Documents\Projects\JellyPy\lib\cherrypy\_cpdispatch.py", line 54, in __call__
>     return self.callable(*self.args, **self.kwargs)
>   File "C:\Users\Jean\Documents\Projects\JellyPy\jellypy\webserve.py", line 528, in get_recently_added
>     result = jellyfin_connect.get_recently_added_details(count=count, media_type=media_type)
>   File "C:\Users\Jean\Documents\Projects\JellyPy\jellypy\jellyconnect.py", line 705, in get_recently_added_details
>     recents = self.get_recently_added_details(start, count, media_type)
>   File "C:\Users\Jean\Documents\Projects\JellyPy\jellypy\jellyconnect.py", line 763, in get_recently_added_details
>     if director["Role"] == "Director":
> KeyError: 'Role'

And the image
https://i.imgur.com/w6uM5mb.png

**Comment by NiNiyas** [comment]
Thanks for opening this issue. Are you on Matrix or Discord? If you are could you please message me so that we can troubleshoot it there?

Matrix: https://matrix.to/#/@spacetornado:thelmc.xyz
Discord: l-TH3_H4CK3R-l #2173

**Comment by Yankees4life** [comment]
> Thanks for opening this issue. Are you on Matrix or Discord? If you are could you please message me so that we can troubleshoot it there?
> 
> Matrix: https://matrix.to/#/@spacetornado:thelmc.xyz Discord: l-TH3_H4CK3R-l #2173

I'm on Discord ATM
